### ISSUE TITLE
quantiles on square transformed densities incorrect

### ISSUE THREAD

**Issue by robjhyndman** [mitchelloharawild/distributional#129]
``` r
library(distributional)
dist_normal()^2 |> hilo()
#> <hilo[1]>
#> [1] [3.841459, 3.841459]95
dist_normal(500,20)^2 |> hilo()
#> Error in `new_hilo()`:
#> ! `upper` can't be lower than `lower`.
```

<sup>Created on 2024-10-04 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Possibly because transformation is not monotonic over sample space of distribution?

**Comment by robjhyndman** [comment]
This is the cause of the problem described at https://forum.posit.co/t/fable-and-distributional-packages-hilo-function-error/193716

**Comment by mitchelloharawild** [comment]
Yes, transformations are assumed monotonic over the support of the distribution.
I can't think of an efficient way to test this yet, currently this test is used: 

https://github.com/mitchelloharawild/distributional/blob/3a721691d597095e27d8ebc53e137d6b4466973a/R/transformed.R#L165-L174

**Comment by mitchelloharawild** [comment]
Also noting that this is mentioned in the documentation of `dist_transformed()`. 

https://github.com/mitchelloharawild/distributional/blob/3a721691d597095e27d8ebc53e137d6b4466973a/R/transformed.R#L10-L11

**Comment by mitchelloharawild** [comment]
This is now patch fixed, essentially since the domain goes from (-Inf, Inf) to [0, Inf) the monotonicity requirement of `dist_transformed()` is violated. Of course for most of the density here it isn't a problem, and the error was due to a boundary condition (defaulting monotonic decreasing rather than increasing).

The better solution requires a symbolic understanding of function monotonicity like:

* expr: `x^2`
* monotonic: `{(-Inf, 0), [0, Inf)}`
